import { useState } from "react";

const emptyForm = { academicYear: new Date().getFullYear(), yearOfStudy: "", semesterNumber: "", name: "", startDate: "", endDate: "" };
export default function SemesterForm({ semester, onSubmit, onCancel, busy }) {
  const [form, setForm] = useState(() => semester ? { academicYear: semester.academicYear, yearOfStudy: semester.yearOfStudy, semesterNumber: semester.semesterNumber, name: semester.name || "", startDate: semester.startDate?.slice(0, 10) || "", endDate: semester.endDate?.slice(0, 10) || "" } : emptyForm); const [error, setError] = useState("");
  function change(key, value) { setError(""); setForm((old) => ({ ...old, [key]: value })); }
  async function submit(event) { event.preventDefault(); const data = { ...form, academicYear: Number(form.academicYear), yearOfStudy: Number(form.yearOfStudy), semesterNumber: Number(form.semesterNumber) }; if (!Number.isInteger(data.academicYear) || !Number.isInteger(data.yearOfStudy) || !Number.isInteger(data.semesterNumber) || data.academicYear < 1 || data.yearOfStudy < 1 || data.semesterNumber < 1) return setError("Use positive whole numbers for the required fields."); if (data.endDate && data.startDate && data.endDate < data.startDate) return setError("End date cannot be before start date."); await onSubmit(data, setError); }
  return <form onSubmit={submit} className="space-y-4 rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><h2 className="text-xl font-bold">{semester ? "Edit semester" : "Create a semester"}</h2><div className="grid gap-4 sm:grid-cols-3"><label className="text-sm font-medium">Academic Year<input required min="1" max="9999" type="number" value={form.academicYear} onChange={(e) => change("academicYear", e.target.value)} className="mt-1 w-full rounded-lg border border-slate-300 p-3" /></label><label className="text-sm font-medium">Year of Study<input required min="1" type="number" value={form.yearOfStudy} onChange={(e) => change("yearOfStudy", e.target.value)} className="mt-1 w-full rounded-lg border border-slate-300 p-3" /></label><label className="text-sm font-medium">Semester Number<input required min="1" type="number" value={form.semesterNumber} onChange={(e) => change("semesterNumber", e.target.value)} className="mt-1 w-full rounded-lg border border-slate-300 p-3" /></label></div><label className="block text-sm font-medium">Name <span className="font-normal text-slate-500">(optional)</span><input maxLength="120" value={form.name} onChange={(e) => change("name", e.target.value)} placeholder="Year 3 Semester 2" className="mt-1 w-full rounded-lg border border-slate-300 p-3" /></label><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Start date <input type="date" value={form.startDate} onChange={(e) => change("startDate", e.target.value)} className="mt-1 w-full rounded-lg border border-slate-300 p-3" /></label><label className="text-sm font-medium">End date <input type="date" value={form.endDate} onChange={(e) => change("endDate", e.target.value)} className="mt-1 w-full rounded-lg border border-slate-300 p-3" /></label></div>{error && <p className="text-sm text-red-700">{error}</p>}<div className="flex gap-3"><button disabled={busy} className="rounded-lg bg-indigo-600 px-5 py-3 font-semibold text-white disabled:opacity-50">{busy ? "Saving…" : semester ? "Save changes" : "Create semester"}</button>{onCancel && <button type="button" onClick={onCancel} disabled={busy} className="rounded-lg px-4 py-3 font-medium text-slate-700">Cancel</button>}</div></form>;
}
