import { useEffect, useState } from "react";
import AppLayout from "../components/layout/AppLayout";
import api from "../services/api";
import { useAuth } from "../context/useAuth";

export default function ProfilePage() {
  const { user, setUser } = useAuth(); const [universities, setUniversities] = useState([]); const [faculties, setFaculties] = useState([]); const [degrees, setDegrees] = useState([]); const [form, setForm] = useState({ universityId: user.universityId || "", facultyId: user.facultyId || "", degreeId: user.degreeId || "", academicYear: user.academicYear || "" }); const [message, setMessage] = useState("");
  useEffect(() => { api.get("/universities").then(({ data }) => setUniversities(data.data.universities)); }, []);
  useEffect(() => { if (form.universityId) api.get(`/universities/${form.universityId}/faculties`).then(({ data }) => setFaculties(data.data.faculties)); }, [form.universityId]);
  useEffect(() => { if (form.facultyId) api.get(`/faculties/${form.facultyId}/degrees`).then(({ data }) => setDegrees(data.data.degrees)); }, [form.facultyId]);
  function update(key, value) { setMessage(""); if (key === "universityId") { setFaculties([]); setDegrees([]); } if (key === "facultyId") setDegrees([]); setForm((old) => ({ ...old, [key]: value, ...(key === "universityId" ? { facultyId: "", degreeId: "" } : {}), ...(key === "facultyId" ? { degreeId: "" } : {}) })); }
  async function submit(event) { event.preventDefault(); try { const { data } = await api.patch("/users/me", { ...form, academicYear: Number(form.academicYear) }); setUser(data.data.user); setMessage("Academic profile saved."); } catch (error) { setMessage(error.response?.data?.message || "Could not save profile."); } }
  return <AppLayout><h1 className="text-3xl font-bold text-slate-900">Academic profile</h1><p className="mt-2 text-slate-600">Keep this information accurate so later tools fit your programme.</p><form onSubmit={submit} className="mt-8 max-w-xl space-y-5 rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><label className="block text-sm font-medium">University<select required value={form.universityId} onChange={(e) => update("universityId", e.target.value)} className="mt-1 w-full rounded-lg border border-slate-300 p-3"><option value="">Choose your university</option>{universities.map((item) => <option key={item._id} value={item._id}>{item.name}</option>)}</select></label><label className="block text-sm font-medium">Faculty<select required disabled={!form.universityId} value={form.facultyId} onChange={(e) => update("facultyId", e.target.value)} className="mt-1 w-full rounded-lg border border-slate-300 p-3"><option value="">Choose your faculty</option>{faculties.map((item) => <option key={item._id} value={item._id}>{item.name}</option>)}</select></label><label className="block text-sm font-medium">Degree<select required disabled={!form.facultyId} value={form.degreeId} onChange={(e) => update("degreeId", e.target.value)} className="mt-1 w-full rounded-lg border border-slate-300 p-3"><option value="">Choose your degree</option>{degrees.map((item) => <option key={item._id} value={item._id}>{item.name}</option>)}</select></label><label className="block text-sm font-medium">Current academic year<input required min="1" max="20" type="number" value={form.academicYear} onChange={(e) => update("academicYear", e.target.value)} className="mt-1 w-full rounded-lg border border-slate-300 p-3" /></label><button className="rounded-lg bg-indigo-600 px-5 py-3 font-semibold text-white">Save profile</button>{message && <p className="text-sm text-slate-600">{message}</p>}</form></AppLayout>;
}
