import { useEffect, useState } from "react";
import AppLayout from "../components/layout/AppLayout";
import SemesterCard from "../components/semester/SemesterCard";
import SemesterForm from "../components/semester/SemesterForm";
import { completeSemester, createSemester, deleteSemester, getSemesters, updateSemester } from "../services/semesterService";

export default function SemestersPage() {
  const [semesters, setSemesters] = useState([]); const [editing, setEditing] = useState(undefined); const [showForm, setShowForm] = useState(false); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  async function load() { try { const { data } = await getSemesters(); setSemesters(data.data.semesters); } catch (error) { setMessage(error.response?.data?.message || "Could not load semesters."); } finally { setLoading(false); } }
  useEffect(() => { getSemesters().then(({ data }) => setSemesters(data.data.semesters)).catch((error) => setMessage(error.response?.data?.message || "Could not load semesters.")).finally(() => setLoading(false)); }, []);
  const active = semesters.find((semester) => semester.status === "active"); const completed = semesters.filter((semester) => semester.status === "completed");
  function beginEdit(semester) { setMessage(""); setEditing(semester); setShowForm(true); }
  async function save(form, setFormError) { setBusy(true); try { if (editing) await updateSemester(editing._id, form); else await createSemester(form); setShowForm(false); setEditing(undefined); setMessage(editing ? "Semester updated." : "Semester created."); await load(); } catch (error) { setFormError(error.response?.data?.message || "Could not save semester."); } finally { setBusy(false); } }
  async function complete(semester) { if (!window.confirm(`Mark ${semester.name || `Year ${semester.yearOfStudy} Semester ${semester.semesterNumber}`} as completed?`)) return; setBusy(true); try { await completeSemester(semester._id); setMessage("Semester marked as completed."); await load(); } catch (error) { setMessage(error.response?.data?.message || "Could not complete semester."); } finally { setBusy(false); } }
  async function remove(semester) { if (!window.confirm("Delete this completed semester? This cannot be undone.")) return; setBusy(true); try { await deleteSemester(semester._id); setMessage("Semester deleted."); await load(); } catch (error) { setMessage(error.response?.data?.message || "Could not delete semester."); } finally { setBusy(false); } }
  return <AppLayout><div className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-3xl font-bold text-slate-900">Semesters</h1><p className="mt-2 text-slate-600">Manage your current semester and preserve completed ones for your academic history.</p></div>{!active && !showForm && <button onClick={() => { setEditing(undefined); setShowForm(true); }} className="rounded-lg bg-indigo-600 px-5 py-3 font-semibold text-white">Create semester</button>}</div>{message && <p role="status" className="mt-5 rounded-lg bg-slate-100 px-4 py-3 text-sm text-slate-700">{message}</p>}{showForm && <div className="mt-8 max-w-2xl"><SemesterForm key={editing?._id || "new"} semester={editing} onSubmit={save} busy={busy} onCancel={() => { setShowForm(false); setEditing(undefined); }} /></div>}{loading ? <p className="mt-8 text-slate-600">Loading semesters…</p> : <><section className="mt-8"><h2 className="text-sm font-bold tracking-wide text-indigo-700">CURRENT SEMESTER</h2><div className="mt-3">{active ? <SemesterCard semester={active} onEdit={beginEdit} onComplete={complete} onDelete={remove} busy={busy} /> : <div className="rounded-2xl border border-dashed border-slate-300 bg-white p-6 text-slate-600">No active semester. Create one when you are ready to begin.</div>}</div></section><section className="mt-10"><h2 className="text-sm font-bold tracking-wide text-slate-700">PREVIOUS SEMESTERS</h2><div className="mt-3 grid gap-4 md:grid-cols-2">{completed.length ? completed.map((semester) => <SemesterCard key={semester._id} semester={semester} onEdit={beginEdit} onComplete={complete} onDelete={remove} busy={busy} />) : <div className="rounded-2xl border border-dashed border-slate-300 bg-white p-6 text-slate-600">{semesters.length ? "No completed semesters yet." : "No semesters yet. Create your first semester to get started."}</div>}</div></section></>}</AppLayout>;
}
