import mongoose from "mongoose";
import Module from "../models/Module.js";
import Semester from "../models/Semester.js";
import LectureSession from "../models/LectureSession.js";
import { ATTENDANCE_THRESHOLD } from "../config/attendance.js";

const validId = mongoose.isValidObjectId;
const fields = ["moduleCode", "moduleName", "credits", "moduleType", "theoryHours", "practicalHours", "isActive"];
function validate(data) { if (typeof data.moduleCode !== "string" || !data.moduleCode.trim()) return "Module code is required"; if (typeof data.moduleName !== "string" || !data.moduleName.trim()) return "Module name is required"; if (!Number.isFinite(data.credits) || data.credits <= 0) return "Credits must be greater than zero"; if (!["theory_only", "theory_practical"].includes(data.moduleType)) return "Choose a valid module type"; if (!Number.isFinite(data.theoryHours) || data.theoryHours < 0) return "Theory hours must be zero or greater"; if (data.moduleType === "theory_practical" && (!Number.isFinite(data.practicalHours) || data.practicalHours < 0)) return "Practical hours must be zero or greater"; return null; }
async function ownedSemester(id, userId) { return validId(id) ? Semester.findOne({ _id: id, userId }) : null; }

export async function createModule(req, res, next) { try { const { semesterId } = req.body; const semester = await ownedSemester(semesterId, req.user.id); if (!semester) return res.status(404).json({ success: false, message: "Semester not found" }); if (semester.status !== "active") return res.status(409).json({ success: false, message: "Cannot add modules to a completed semester" }); const input = { moduleCode: req.body.moduleCode, moduleName: req.body.moduleName, credits: req.body.credits, moduleType: req.body.moduleType, theoryHours: req.body.theoryHours, practicalHours: req.body.moduleType === "theory_only" ? 0 : req.body.practicalHours }; const message = validate(input); if (message) return res.status(400).json({ success: false, message }); const module = await Module.create({ ...input, userId: req.user.id, semesterId, attendanceThreshold: ATTENDANCE_THRESHOLD }); res.status(201).json({ success: true, data: { module } }); } catch (error) { if (error.code === 11000) return res.status(409).json({ success: false, message: "This module code already exists in the semester" }); next(error); } }
export async function listModules(req, res, next) { try { const { semesterId } = req.query; const semester = await ownedSemester(semesterId, req.user.id); if (!semester) return res.status(404).json({ success: false, message: "Semester not found" }); const modules = await Module.find({ userId: req.user.id, semesterId }).sort({ moduleCode: 1 }).lean(); res.json({ success: true, data: { modules } }); } catch (error) { next(error); } }
export async function getModule(req, res, next) { try { if (!validId(req.params.id)) return res.status(400).json({ success: false, message: "Invalid module identifier" }); const module = await Module.findOne({ _id: req.params.id, userId: req.user.id }).lean(); if (!module) return res.status(404).json({ success: false, message: "Module not found" }); res.json({ success: true, data: { module } }); } catch (error) { next(error); } }
export async function updateModule(req, res, next) { try { if (!validId(req.params.id)) return res.status(400).json({ success: false, message: "Invalid module identifier" }); const module = await Module.findOne({ _id: req.params.id, userId: req.user.id }); if (!module) return res.status(404).json({ success: false, message: "Module not found" }); const semester = await ownedSemester(module.semesterId, req.user.id); if (semester.status !== "active") return res.status(409).json({ success: false, message: "Cannot change modules in a completed semester" }); const updates = Object.fromEntries(Object.entries(req.body).filter(([key]) => fields.includes(key))); const candidate = { ...module.toObject(), ...updates }; if (candidate.moduleType === "theory_only") candidate.practicalHours = 0; const message = validate(candidate); if (message) return res.status(400).json({ success: false, message }); if (module.moduleType === "theory_practical" && candidate.moduleType === "theory_only" && await LectureSession.exists({ moduleId: module._id, sessionType: "practical" })) return res.status(409).json({ success: false, message: "Remove practical sessions before changing this module to theory only" }); module.set(updates); if (module.moduleType === "theory_only") module.practicalHours = 0; await module.save(); res.json({ success: true, data: { module } }); } catch (error) { if (error.code === 11000) return res.status(409).json({ success: false, message: "This module code already exists in the semester" }); next(error); } }
export async function deleteModule(req, res, next) { try { if (!validId(req.params.id)) return res.status(400).json({ success: false, message: "Invalid module identifier" }); const module = await Module.findOne({ _id: req.params.id, userId: req.user.id }); if (!module) return res.status(404).json({ success: false, message: "Module not found" }); if (await LectureSession.exists({ moduleId: module._id })) return res.status(409).json({ success: false, message: "Delete this module's lecture sessions before deleting the module" }); await module.deleteOne(); res.json({ success: true, data: null }); } catch (error) { next(error); } }
